# Utiliza una imagen base de Java (por ejemplo, OpenJDK) con la versión que necesites
FROM openjdk:11

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo JAR de tu aplicación al contenedor >> HASTA QUE NO TENGAMOS EL JAR LISTO NO LO DESCOMENTAMOS
#COPY mi_app.jar /app/mi_app.jar

# Expone el puerto que tu aplicación escucha (por ejemplo, 8080)
EXPOSE 8080

# Comando para ejecutar tu aplicación cuando se ejecute el contenedor >> HASTA QUE NO TENGAMOS EL JAR LISTO NO LO DESCOMENTAMOS
#CMD ["java", "-jar", "mi_app.jar"]
